Сетка новостей
elena-delikanova/prozhito pull request #24
Opened 2022-07-16 18:30 UTC by elena-delikanova

2022-07-16 18:30 UTC, elena-delikanova commented
@kur0yuki,

посмотри, пожалуйста.

Я включила красные границы для всех блоков, чтобы было лучше видно, перед мержом уберу

2022-07-16 18:55 UTC, kur0yuki requested changes

2022-07-16 18:55 UTC, kur0yuki commented on blocks/all-news/__item/all-news__item.css
> +
Лучше использовать min-height, или убрать и отдать контроль над высотой реализации карт новости

2022-07-16 18:55 UTC, kur0yuki commented on blocks/all-news/__list/all-news__list.css
> +    padding: 0 12px 84px;
Зачем такой пэддинг снизу?

2022-07-16 18:55 UTC, kur0yuki commented on blocks/all-news/__list/all-news__list.css
> +    grid-template-columns: repeat(1, 1fr);
repeat не нужен

2022-07-16 18:55 UTC, kur0yuki commented on blocks/all-news/all-news.css
> +}
Будет красивее добавить еще padding по бокам для экранов 768 - 1200

2022-07-17 17:25 UTC, elena-delikanova commented on blocks/all-news/__item/all-news__item.css
> +
По идее, высота должна быть за счет карточки новости, да. Но я на всякий пока оставила. Напишу в задачу на верстку карточки новостей, что по возможности надо убрать

2022-07-17 17:27 UTC, elena-delikanova commented on blocks/all-news/__list/all-news__list.css
> +    padding: 0 12px 84px;
Сделала по аналогии с вот этим:

![image](https://user-images.githubusercontent.com/22788947/179417541-725ecfaa-b030-428d-b5d2-1efe6753b7a7.png)

Т.к. нормального макета для адаптива нет, мы можем только предполагать, как оно там будет

2022-07-17 17:27 UTC, elena-delikanova commented on blocks/all-news/__list/all-news__list.css
> +    grid-template-columns: repeat(1, 1fr);
Согласна, убрала

2022-07-17 17:32 UTC, elena-delikanova commented on blocks/all-news/all-news.css
> +}
А какие значения ставить? 🤔

2022-07-17 21:27 UTC, kur0yuki commented on blocks/all-news/__list/all-news__list.css
> +    padding: 0 12px 84px;
> Сделала по аналогии с вот этим:

Это тогда должен быть верхний отступ блока снизу, как в начале договаривались

2022-07-28 20:57 UTC, elena-delikanova commented on blocks/all-news/__list/all-news__list.css
> +    padding: 0 12px 84px;
Убрала

2022-07-28 21:10 UTC, merged